### ISSUE TITLE
Cannot open Docs

### ISSUE THREAD

**Issue by Pixdigit** [vncastanheira/gjapi_python#1]
Clicking on the index.html opens code viewer.

**Comment by vncastanheira** [comment]
Just set to open on your browser. Tried to open on Firefox and worked just fine.

**Comment by Pixdigit** [comment]
What do you mean by "set to open"?

**Comment by vncastanheira** [comment]
@Pixdigit Open the file in your browser and it will work.

**Comment by Pixdigit** [comment]
So I should download it and open it then?
Am 09.07.2015 17:51 schrieb "Vinícius" <notifications@github.com>:

**Comment by vncastanheira** [comment]
@Pixdigit Of course.

**Comment by Pixdigit** [comment]
Sorry, I was just unsure if all dependencies still work because often they
dont. Thanks for helping though.
Am 09.07.2015 21:17 schrieb "Vinícius" <notifications@github.com>:

**Comment by vncastanheira** [comment]
@Pixdigit No problem! 
Let me know if something is broken.
