### ISSUE TITLE
License

### ISSUE THREAD

**Issue by CyberKiller40** [vncastanheira/gjapi_python#4]
Hello, I tried asking in the forum thread on GJ about the license for this code, but didn't get any response.
http://gamejolt.com/f/python-module-for-gjapi/1362

It's important for me to know what I can do with this code, especially because I license my own stuff under the GNU GPL.

Here are some hints to make this easier for you:
If you don't care then just assign some kind of very permissive license like public domain, CC0, BSD or WTFPL.
If you care a little, want attributtion, etc, then maybe one of MIT, LGPL or zlib will be more to your linking.
Other open source licenses are ok too.

The whole point is that without explicitly stated license your code is "all rights reserved" meaning nobody can legally use it in their projects.

**Comment by CyberKiller40** [comment]
I just noticed there is a note about LGPL in the beginning of the script. Sorry for bothering you, I never thought to look there and I didn't see any info in the readme or otherwise.

**Comment by vncastanheira** [comment]
That's ok, but I replied a few days ago on GameJolt forums.
Indeed licensing is a important matter, so it will be on the README file from now on.
